version: "3.9"
services:
  api:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      db:
        condition: service_healthy
    command: [ "air", "-c", ".air.toml" ]
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: developer
      DB_PASSWORD: password
      DB_NAME: TASCHOLA
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    container_name: db
    hostname: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TASCHOLA
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "mysql",
          "-pmysql"
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
